### ISSUE TITLE
Item drawer

### ISSUE THREAD

**Issue by adityasimant** [IgnitePluse/Ignite#8]
Make a sliding drawer in MainActivity.java .

**Comment by DevPJ9** [comment]
Hello, @adityasimant I would like to contribute. Can you please explain what Is the sliding drawer requirement?

**Comment by adityasimant** [comment]
Make a sliding navigation just like this example. Add setting, logout,
licence and privacy policy.
If you can, logout the user when clicked on logout ( there already code
written in the MainActivity, you just have to cut paste it. ) Reply to
this  email and I will assign you the task.

**Comment by adityasimant** [comment]
Make a sliding navigation drawer just like in Gmail. Add setting, logout,
license and privacy policy.
If you can, logout the user when clicked on logout ( there already code
written in the MainActivity, you just have to cut paste it. )
